Services must on go whatever error occurred

diff --git a/app/etc/init.d/wlan2 b/app/etc/init.d/wlan2
--- a/app/etc/init.d/wlan2
+++ b/app/etc/init.d/wlan2
@@ -35,7 +35,7 @@ SDIO_POLLING_PATH="/sys/devices/msm_sdcc.3/polling"
 HOSTAPD_CONF="/etc/wlan2/hostapd.conf"
 WPA_SUPPLICANT_CONF="/etc/wlan2/wpa_supplicant.conf"
 
-set -e
+#set -e
 
 if [ -r $CONF_FILE ]; then
 
@@ -47,6 +47,7 @@ if [ -r $CONF_FILE ]; then
 
     case "$1" in
     start)
+        $0 stop
         
         if [ -w $SDIO_POLLING_PATH ]; then
             echo 1 > $SDIO_POLLING_PATH
@@ -70,12 +71,11 @@ if [ -r $CONF_FILE ]; then
         
 
         wpa_supplicant -B -Dar6003 -iwlan0 -c$WPA_SUPPLICANT_CONF
-        udhcpc -n -i wlan0 -s /etc/udhcpc.d/50default
-        
-        if [ $? -ne 0 ];then
-            echo "Error wifi auth fail"
-            exit 1
-        fi
+        #udhcpc -n -i wlan0 -s /etc/udhcpc.d/50default
+        #if [ $? -ne 0 ];then
+        #    echo "Error wifi auth fail"
+        #    exit 1
+        #fi
         
         ping -q -c 1 -W 1 1.1.1.1
         if [ $? -ne 0 ];then
@@ -89,7 +89,7 @@ if [ -r $CONF_FILE ]; then
 
     stop)
         echo "Stopping WLAN..."
-        killall -15 cxmapp hostapd dhcprelay wpa_supplicant udhcpc 2>/dev/null
+        killall -15 cxmapp hostapd dhcprelay wpa_supplicant udhcpc QCMAP_ConnectionManager 2>/dev/null &
         echo 0 > $SDIO_POLLING_PATH
         rmmod ar6000
         ;;
